// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1BsblVig55hnLLYV_6Mabu0Gp3vRrDwM',
    appId: '1:612873124524:web:dc548e22eb5580ac843d09',
    messagingSenderId: '612873124524',
    projectId: 'chat-application-5d43e',
    authDomain: 'chat-application-5d43e.firebaseapp.com',
    storageBucket: 'chat-application-5d43e.appspot.com',
    measurementId: 'G-FPS62LGG4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMEggs9dsWElxgX1Fbaz8MjESzRwYrOEw',
    appId: '1:612873124524:android:495f3cd104ff038e843d09',
    messagingSenderId: '612873124524',
    projectId: 'chat-application-5d43e',
    storageBucket: 'chat-application-5d43e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnMgCXxHPsRjzpjbaMADwXxEncbyOFDgY',
    appId: '1:612873124524:ios:7496edd9d35c5a2e843d09',
    messagingSenderId: '612873124524',
    projectId: 'chat-application-5d43e',
    storageBucket: 'chat-application-5d43e.appspot.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnMgCXxHPsRjzpjbaMADwXxEncbyOFDgY',
    appId: '1:612873124524:ios:7496edd9d35c5a2e843d09',
    messagingSenderId: '612873124524',
    projectId: 'chat-application-5d43e',
    storageBucket: 'chat-application-5d43e.appspot.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1BsblVig55hnLLYV_6Mabu0Gp3vRrDwM',
    appId: '1:612873124524:web:216ebbc3bc20794f843d09',
    messagingSenderId: '612873124524',
    projectId: 'chat-application-5d43e',
    authDomain: 'chat-application-5d43e.firebaseapp.com',
    storageBucket: 'chat-application-5d43e.appspot.com',
    measurementId: 'G-0W253HBCDB',
  );
}
